/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "fileserver.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_read_1 (read_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (read_1_svc(argp->arg1, argp->position, argp->cant, result, rqstp));
}

int
_write_1 (write_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (write_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_size_1 (filename  *argp, void *result, struct svc_req *rqstp)
{
	return (size_1_svc(*argp, result, rqstp));
}

static void
fileserver_program_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		read_1_argument read_1_arg;
		write_1_argument write_1_arg;
		filename size_1_arg;
	} argument;
	union {
		filedata read_1_res;
		int write_1_res;
		int size_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case read:
		_xdr_argument = (xdrproc_t) xdr_read_1_argument;
		_xdr_result = (xdrproc_t) xdr_filedata;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_read_1;
		break;

	case write:
		_xdr_argument = (xdrproc_t) xdr_write_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_write_1;
		break;

	case size:
		_xdr_argument = (xdrproc_t) xdr_filename;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_size_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!fileserver_program_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (FILESERVER_PROGRAM, FILESERVER_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, FILESERVER_PROGRAM, FILESERVER_VERSION, fileserver_program_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (FILESERVER_PROGRAM, FILESERVER_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, FILESERVER_PROGRAM, FILESERVER_VERSION, fileserver_program_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (FILESERVER_PROGRAM, FILESERVER_VERSION, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
