/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fileserver.h"


CLIENT *clnt;

char* get_pathname(filename name){
    char *pathname = (char *)malloc((strlen(FOLDER_CLIENT) + strlen(name)) * sizeof(char));
    sprintf(pathname, "%s%s",FOLDER_CLIENT, name);
    return pathname;
}

int writeFileLocal(filename name, filedata data)
{
	int result;
    char *pathname = get_pathname(name);
	FILE *file = fopen(pathname, "ab");
    result = fwrite(data.filedata_val, sizeof(char), data.filedata_len, file);
	fclose(file);
    free(pathname);
	return result;
}

void pre_rpc(char *host, char *protocol)
{
	#ifndef	DEBUG
		clnt = clnt_create (host, FILESERVER_PROGRAM, FILESERVER_VERSION, protocol);
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */

}

void post_rpc()
{
	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */
}

void check_retval(enum clnt_stat retval, CLIENT *clnt)
{
	if (retval != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
		exit(1);
	}

}

void copyFile(filename filename_server, filename filename_client){
	enum clnt_stat retval;
	filedata result;
	int sizeFile;

	retval = size_1(filename_server, &sizeFile, clnt);
	check_retval(retval, clnt);

	if(sizeFile > -1) {
		result.filedata_len = 0;
		result.filedata_val = (char *)calloc(sizeFile, sizeof(char));
		retval = read_1(filename_server, 0, sizeFile, &result, clnt);
		check_retval(retval, clnt);

		printf("la cantidad de bytes leidos es: %d \n", result.filedata_len);


		int bytesEscritos = 0;
		//char *pathname = get_pathname(filename_client);
		retval = write_1(filename_client, result, &bytesEscritos, clnt);
		check_retval(retval, clnt);

		printf("bytesEscritos = %d\n", bytesEscritos);

		writeFileLocal(filename_client, result);

		free(result.filedata_val);
	
	} else {
		fprintf(stderr, "%s", "File Not Found!\n");
		exit(1);
	}



}


int main (int argc, char *argv[])
{

	if (argc != 4) {
    	fprintf(stderr,"Usage: %s hostname_server filename_server filename_client \n",argv[0]);
    	exit(1);
  	}

	char *host = argv[1];
	filename filename_server = argv[2];
	filename filename_client = argv[3];

	pre_rpc(host, "tcp");
	copyFile(filename_server, filename_client);
	post_rpc();
	exit (0);
}
