/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILESERVER_H_RPCGEN
#define _FILESERVER_H_RPCGEN

/* BEGIN DEFINES CLIENT/SERVER */

#define FOLDER_SERVER "files_server/"
#define FOLDER_CLIENT "files_client/"

/* END DEFINES CLIENT/SERVER */


#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int filedata_len;
	char *filedata_val;
} filedata;

typedef char *filename;

struct read_1_argument {
	filename arg1;
	int position;
	int cant;
};
typedef struct read_1_argument read_1_argument;

struct write_1_argument {
	filename arg1;
	filedata arg2;
};
typedef struct write_1_argument write_1_argument;

#define FILESERVER_PROGRAM 0x20000001
#define FILESERVER_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define read 1
extern  enum clnt_stat read_1(filename , int , int , filedata *, CLIENT *);
extern  bool_t read_1_svc(filename , int , int , filedata *, struct svc_req *);
#define write 2
extern  enum clnt_stat write_1(filename , filedata , int *, CLIENT *);
extern  bool_t write_1_svc(filename , filedata , int *, struct svc_req *);
#define size 3
extern  enum clnt_stat size_1(filename , int *, CLIENT *);
extern  bool_t size_1_svc(filename , int *, struct svc_req *);
extern int fileserver_program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define read 1
extern  enum clnt_stat read_1();
extern  bool_t read_1_svc();
#define write 2
extern  enum clnt_stat write_1();
extern  bool_t write_1_svc();
#define size 3
extern  enum clnt_stat size_1();
extern  bool_t size_1_svc();
extern int fileserver_program_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_filedata (XDR *, filedata*);
extern  bool_t xdr_filename (XDR *, filename*);
extern  bool_t xdr_read_1_argument (XDR *, read_1_argument*);
extern  bool_t xdr_write_1_argument (XDR *, write_1_argument*);

#else /* K&R C */
extern bool_t xdr_filedata ();
extern bool_t xdr_filename ();
extern bool_t xdr_read_1_argument ();
extern bool_t xdr_write_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILESERVER_H_RPCGEN */
