/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "fileserver.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
read_1(filename arg1, int position, int cant, filedata *clnt_res,  CLIENT *clnt)
{
	read_1_argument arg;
	arg.arg1 = arg1;
	arg.position = position;
	arg.cant = cant;
	return (clnt_call (clnt, read, (xdrproc_t) xdr_read_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_filedata, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
write_1(filename arg1, filedata arg2, int *clnt_res,  CLIENT *clnt)
{
	write_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, write, (xdrproc_t) xdr_write_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
size_1(filename arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, size,
		(xdrproc_t) xdr_filename, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
